image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ~/.terraform.d/plugins
  - curl -L https://github.com/gig-tech/terraform-provider-ovc/releases/download/v0.0.1/terraform-provider-ovc_v0.0.1-linux -o ~/.terraform.d/plugins/terraform-provider-ovc
  - curl -L https://github.com/nbering/terraform-provider-ansible/releases/download/v0.0.4/terraform-provider-ansible-linux_amd64.zip -o terraform-provider-ansible-linux_amd64.zip && unzip terraform-provider-ansible-linux_amd64.zip
  - mv linux_amd64/terraform-provider-ansible_v0.0.4 ~/.terraform.d/plugins/terraform-provider-ansible
  - chmod a+x ~/.terraform.d/plugins/*
  - ls -l ~/.terraform.d/plugins/*
  - ls -l /root/.terraform.d/plugins
  - ls -dl /root
  - ls -dl /root/.terraform.d
  - ls -dl /root/.terraform.d/plugins
  - mkdir -p ./creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  - cd terraform
  - id
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual