---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: "Create ansible user and configure access"
      user:
        name: ansible
        comment: "Ansible user"
        shell: '/bin/bash'

    - name: Set authorized key taken from file
      authorized_key:
        user: ansible
        state: present
        exclusive: True
        key: '{{ item }}'
      with_file:
        - public_keys/ansible

    - name: Install sudo config for ansible user
      copy:
        src: files/sudo_ansible
        dest: /etc/sudoers.d/90-ansible
        owner: root
        group: root
        mode: 0644
